---

logging:
  level:
    root: INFO

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: false