---

logging:
  level:
    root: WARN

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  output:
    ansi:
      enabled: always
  profiles:
    default: development
  instancio:
    bean:
      validation:
        enabled: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1