---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://taskmanageronspring_user:3MCGi0BamwU85r5fMn6sf2e5O1uc1FaS@dpg-ctgpqtij1k6c73a5dea0-a/taskmanageronspring
    dialect_class_name: org.postgresql.Driver
    username: taskmanageronspring_user
    password: 3MCGi0BamwU85r5fMn6sf2e5O1uc1FaS
    port: 5432
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      generate-ddl: true