---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  output:
    ansi:
      enabled: always
  instancio:
    bean:
      validation:
        enabled: true
logging:
  level:
    root: WARN