---

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://dpg-cu57c5tds78s73e0rqrg-a:5432/updatedtaskmanageronspring
    driver-class-name: org.postgresql.Driver
    username: updatedtaskmanageronspring_user
    password: DC613unqgMzjVNp6XPwEZk0mqzGlRU0d
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false