---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://dpg-ctgpqtij1k6c73a5dea0-a:5432/taskmanageronspring
    driver-class-name: org.postgresql.Driver
    username: taskmanageronspring_user
    password: 3MCGi0BamwU85r5fMn6sf2e5O1uc1FaS
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: false
logging:
  level:
    root: INFO